apiVersion: v1
kind: Service
metadata:
  name: microkv-service
spec:
  clusterIP: None # Required for peer DNS resolution
  selector:
    app: microkv
  ports:
    - port: 8080
      targetPort: 8080
